name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/e-commerce-api:latest

      # Step 5: Deploy to Server
      - name: Deploy to Server
        run: |
          # Save the SSH private key into a temporary file 
          echo "$SSH_PRIVATE_KEY" > /tmp/id_rsa
    
          # Set the correct permissions for the private key
          chmod 600 /tmp/id_rsa
    
          # Use the private key file with SSH to connect and run commands on the server
          ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no ec2-user@34.235.117.108 << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/e-commerce-api:latest
          docker stop nest-app || true
          docker rm nest-app || true
          docker run -d --name nest-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/e-commerce-api:latest
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Add private SSH key to GitHub secrets
